const mongoose = require("mongoose");

const tripSchema = new mongoose.Schema(
  {
    userId: {
      type: String,
      required: true,
      index: true
    },

    source: {
      type: String,
      required: true,
      trim: true
    },

    destination: {
      type: String,
      required: true,
      trim: true
    },

    mode: {
      type: String,
      required: true,
      enum: ["Flight", "Train", "Car", "Bus", "Other"]
    },

    budget: {
      type: Number,
      required: true,
      min: 0
    },

    style: {
      type: String,
      enum: ["Luxury", "Balanced", "Budget", "Adventure"],
      default: "Balanced"
    },

    days: {
      type: Number,
      default: 2,
      min: 1
    },

    departureTime: {
      type: String
    },

    itinerary: {
      type: String,
      default: ""
    },

    carbon: {
      type: Number,
      default: 0
    },

    locationHint: {
      type: String
    },

    // Structured timeline generated from itinerary
    timeline: {
      type: Object,
      default: {}
    },

    // Smart reminders generated by backend
    reminders: {
      type: [String],
      default: []
    },

    // Trip intelligence report
    report: {
      type: Object,
      default: {}
    },

    // Ticket information if trip was created via OCR
    ticketInfo: {
      pnr: { type: String },
      rawText: { type: String },
      parsedAt: { type: Date }
    },

    // Track lifecycle of a trip
    tripStatus: {
      type: String,
      enum: ["planned", "ongoing", "completed"],
      default: "planned"
    }
  },
  {
    timestamps: true
  }
);

module.exports = mongoose.model("Trip", tripSchema);